# Generated by Django 2.0.3 on 2018-05-06 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admi',
            new_name='Admin',
        ),
    ]
