# Generated by Django 2.0.3 on 2018-05-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180506_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='logo',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='p_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Parties'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='voters_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vote.Voters'),
        ),
    ]
